/**
 * SHA-256 helpers for high-entropy bearer secrets (invite tokens,
 * recovery codes, API keys' raw secret part). We do NOT use Argon2 here
 * because the secret is generated by us with full entropy — the slow
 * key-derivation function exists to defend low-entropy human-chosen
 * passwords. SHA-256 is the right tool for high-entropy random bytes.
 *
 * Passwords use a different module (`./password.ts`, Argon2id). Don't
 * cross-wire them.
 */

import { createHash, randomBytes, timingSafeEqual } from 'node:crypto';

/**
 * Generate an opaque high-entropy secret. 32 bytes encoded as URL-safe
 * base64 → 43 chars, ~256 bits of entropy. Surfaced to the operator
 * EXACTLY ONCE (invite issue) or EXACTLY ONCE per regeneration (recovery
 * codes).
 */
export function generateSecret(): string {
  return randomBytes(32).toString('base64url');
}

export function hashSecret(secret: string): string {
  return createHash('sha256').update(secret).digest('hex');
}

/**
 * Deterministic prefix used to bound candidate-row scans during verify.
 * We use the first 8 hex chars of the hash — tens of thousands of
 * pending invites would still average <1 collision per lookup. Treated
 * as low-cardinality on purpose.
 */
export function lookupOf(secret: string): string {
  return hashSecret(secret).slice(0, 8);
}

export function constantTimeEqual(a: string, b: string): boolean {
  const ab = Buffer.from(a, 'utf8');
  const bb = Buffer.from(b, 'utf8');
  if (ab.length !== bb.length) return false;
  return timingSafeEqual(ab, bb);
}
