/**
 * SHA-256 helpers for high-entropy bearer secrets (invite tokens,
 * recovery codes, API keys' raw secret part). We do NOT use Argon2 here
 * because the secret is generated by us with full entropy — the slow
 * key-derivation function exists to defend low-entropy human-chosen
 * passwords. SHA-256 is the right tool for high-entropy random bytes.
 *
 * Passwords use a different module (`./password.ts`, Argon2id). Don't
 * cross-wire them.
 */

import { getIdentityCrypto } from './runtime.ts';

/**
 * Generate an opaque high-entropy secret. 32 bytes encoded as URL-safe
 * base64 → 43 chars, ~256 bits of entropy. Surfaced to the operator
 * EXACTLY ONCE (invite issue) or EXACTLY ONCE per regeneration (recovery
 * codes).
 */
export function generateSecret(): string {
  return base64url(getIdentityCrypto().randomBytes(32));
}

export function hashSecret(secret: string): string {
  return toHex(getIdentityCrypto().sha256(secret));
}

/**
 * Deterministic prefix used to bound candidate-row scans during verify.
 * We use the first 8 hex chars of the hash — tens of thousands of
 * pending invites would still average <1 collision per lookup. Treated
 * as low-cardinality on purpose.
 */
export function lookupOf(secret: string): string {
  return hashSecret(secret).slice(0, 8);
}

export function constantTimeEqual(a: string, b: string): boolean {
  const ab = new TextEncoder().encode(a);
  const bb = new TextEncoder().encode(b);
  if (ab.length !== bb.length) return false;
  return getIdentityCrypto().timingSafeEqual(ab, bb);
}

function base64url(bytes: Uint8Array): string {
  let str = '';
  for (let i = 0; i < bytes.length; i += 1) str += String.fromCharCode(bytes[i]!);
  return globalThis
    .btoa(str)
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');
}

function toHex(bytes: Uint8Array): string {
  let s = '';
  for (let i = 0; i < bytes.length; i += 1)
    s += bytes[i]!.toString(16).padStart(2, '0');
  return s;
}
