import {
  mkdirSync,
  copyFileSync,
  readdirSync,
  writeFileSync,
  statSync,
} from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const repoRoot = resolve(__dirname, '..', '..', '..');
const contracts = join(repoRoot, 'specs', 'schemas', 'contracts');
const events = join(repoRoot, 'specs', 'schemas', 'events');
const modulesDir = join(repoRoot, 'specs', 'modules');
const seedDir = join(modulesDir, 'structured-catalog', 'seed-packages');

const outDir = resolve(__dirname, '..', 'src', 'generated');
const manifestsOutDir = join(outDir, 'manifests');
mkdirSync(outDir, { recursive: true });
mkdirSync(manifestsOutDir, { recursive: true });

const copied: string[] = [];

// Copy module-domain schemas (`catalog.*`, `authz.*`, `content_pages.*`) and
// platform-emitted ones (`platform.*` — e.g. StructuredAuthz.PolicyEvaluated
// audit events).
const isPicked = (n: string): boolean =>
  (n.startsWith('catalog.') ||
    n.startsWith('platform.') ||
    n.startsWith('authz.') ||
    n.startsWith('content_pages.')) &&
  n.endsWith('.schema.json');

for (const dir of [contracts, events]) {
  for (const f of readdirSync(dir)) {
    if (isPicked(f)) {
      copyFileSync(join(dir, f), join(outDir, f));
      copied.push(f);
    }
  }
}

copyFileSync(join(seedDir, 'badge-family.json'), join(outDir, 'badge-family.json'));
copied.push('badge-family.json');

// Discover per-module manifests under `specs/modules/<moduleId>/module.manifest.json`.
// Each is copied into `generated/manifests/<moduleId>.manifest.json` so the
// loader can import them statically as a stable, deterministic set.
const manifestFiles: string[] = [];
for (const entry of readdirSync(modulesDir)) {
  const entryPath = join(modulesDir, entry);
  let isDir = false;
  try {
    isDir = statSync(entryPath).isDirectory();
  } catch {
    continue;
  }
  if (!isDir) continue;
  const manifestPath = join(entryPath, 'module.manifest.json');
  let manifestExists = false;
  try {
    manifestExists = statSync(manifestPath).isFile();
  } catch {
    manifestExists = false;
  }
  if (!manifestExists) continue;
  const outName = `${entry}.manifest.json`;
  copyFileSync(manifestPath, join(manifestsOutDir, outName));
  manifestFiles.push(outName);
  copied.push(`manifests/${outName}`);
}
manifestFiles.sort();

const indexLines = ['// Auto-generated by scripts/sync-schemas.ts. Do not edit.'];
indexLines.push(
  `export const generatedFiles: ReadonlyArray<string> = ${JSON.stringify(copied.sort(), null, 2)};`,
);
indexLines.push(
  `export const moduleManifestFiles: ReadonlyArray<string> = ${JSON.stringify(manifestFiles, null, 2)};`,
);
writeFileSync(join(outDir, 'index.ts'), indexLines.join('\n') + '\n');

console.log(
  `Copied ${copied.length} files to ${outDir} (${manifestFiles.length} module manifests)`,
);
