import { mkdirSync, copyFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const repoRoot = resolve(__dirname, '..', '..', '..');
const contracts = join(repoRoot, 'specs', 'schemas', 'contracts');
const events = join(repoRoot, 'specs', 'schemas', 'events');
const seedDir = join(repoRoot, 'specs', 'modules', 'structured-catalog', 'seed-packages');
const moduleManifest = join(
  repoRoot,
  'specs',
  'modules',
  'structured-catalog',
  'module.manifest.json'
);

const outDir = resolve(__dirname, '..', 'src', 'generated');
mkdirSync(outDir, { recursive: true });

const copied: string[] = [];

// Copy module-domain schemas (`catalog.*`, `authz.*`, `content_pages.*`) and
// platform-emitted ones (`platform.*` — e.g. StructuredAuthz.PolicyEvaluated
// audit events).
const isPicked = (n: string): boolean =>
  (n.startsWith('catalog.') ||
    n.startsWith('platform.') ||
    n.startsWith('authz.') ||
    n.startsWith('content_pages.')) &&
  n.endsWith('.schema.json');

for (const dir of [contracts, events]) {
  for (const f of readdirSync(dir)) {
    if (isPicked(f)) {
      copyFileSync(join(dir, f), join(outDir, f));
      copied.push(f);
    }
  }
}

copyFileSync(join(seedDir, 'badge-family.json'), join(outDir, 'badge-family.json'));
copied.push('badge-family.json');
copyFileSync(join(moduleManifest), join(outDir, 'module.manifest.json'));
copied.push('module.manifest.json');

const indexLines = ['// Auto-generated by scripts/sync-schemas.ts. Do not edit.'];
indexLines.push(`export const generatedFiles: ReadonlyArray<string> = ${JSON.stringify(copied.sort(), null, 2)};`);
writeFileSync(join(outDir, 'index.ts'), indexLines.join('\n') + '\n');

console.log(`Copied ${copied.length} files to ${outDir}`);
