/**
 * Identity error taxonomy. Mirrors `@atlas/authz` and
 * `@atlas/content-pages`: a `code` (taxonomy string), human message,
 * suggested HTTP status. The wiring layer maps these to error envelopes.
 */

export const codes = {
  // Phase A1
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_SUSPENDED: 'USER_SUSPENDED',
  MEMBERSHIP_NOT_FOUND: 'MEMBERSHIP_NOT_FOUND',
  MEMBERSHIP_REQUIRED: 'MEMBERSHIP_REQUIRED',
  INVITE_NOT_FOUND: 'INVITE_NOT_FOUND',
  INVITE_EXPIRED: 'INVITE_EXPIRED',
  INVITE_ALREADY_USED: 'INVITE_ALREADY_USED',
  INVITE_REASON_REQUIRED: 'INVITE_REASON_REQUIRED',
  PASSWORD_INVALID: 'PASSWORD_INVALID',
  PASSWORD_COMPLEXITY: 'PASSWORD_COMPLEXITY',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  RATE_LIMITED: 'RATE_LIMITED',
  IDENTITY_INVALID: 'IDENTITY_INVALID',
  // Phase A2 — sessions
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  SESSION_REUSE_DETECTED: 'SESSION_REUSE_DETECTED',
  SESSION_HARD_TIMEOUT: 'SESSION_HARD_TIMEOUT',
  SESSION_IDLE_TIMEOUT: 'SESSION_IDLE_TIMEOUT',
  CSRF_FAILED: 'CSRF_FAILED',
  // Phase A2 — API keys + service principals
  API_KEY_NOT_FOUND: 'API_KEY_NOT_FOUND',
  API_KEY_REVOKED: 'API_KEY_REVOKED',
  API_KEY_EXPIRED: 'API_KEY_EXPIRED',
  API_KEY_SCOPE_INSUFFICIENT: 'API_KEY_SCOPE_INSUFFICIENT',
  API_KEY_MALFORMED: 'API_KEY_MALFORMED',
  SERVICE_PRINCIPAL_NOT_FOUND: 'SERVICE_PRINCIPAL_NOT_FOUND',
  SERVICE_PRINCIPAL_DISABLED: 'SERVICE_PRINCIPAL_DISABLED',
  SERVICE_PRINCIPAL_SCOPE_EXCEEDED: 'SERVICE_PRINCIPAL_SCOPE_EXCEEDED',
  // Phase A2 — OAuth (RFC 6749 error code shape: snake_case strings —
  // wire layer maps these to the OAuth-spec `error` field on the token
  // response).
  OAUTH_INVALID_GRANT: 'OAUTH_INVALID_GRANT',
  OAUTH_INVALID_CLIENT: 'OAUTH_INVALID_CLIENT',
  OAUTH_INVALID_SCOPE: 'OAUTH_INVALID_SCOPE',
  OAUTH_UNSUPPORTED_GRANT_TYPE: 'OAUTH_UNSUPPORTED_GRANT_TYPE',
  OAUTH_TOKEN_EXPIRED: 'OAUTH_TOKEN_EXPIRED',
  OAUTH_TOKEN_REVOKED: 'OAUTH_TOKEN_REVOKED',
  // Phase A3 — federated OIDC.
  IDP_NOT_FOUND: 'IDP_NOT_FOUND',
  IDP_DISABLED: 'IDP_DISABLED',
  IDP_DISCOVERY_FAILED: 'IDP_DISCOVERY_FAILED',
  IDP_KID_UNKNOWN: 'IDP_KID_UNKNOWN',
  IDP_INVALID_CONFIG: 'IDP_INVALID_CONFIG',
  IDP_ISSUER_CONFLICT: 'IDP_ISSUER_CONFLICT',
  JIT_PROVISIONING_DISABLED: 'JIT_PROVISIONING_DISABLED',
  JWT_AUDIENCE_MISMATCH: 'JWT_AUDIENCE_MISMATCH',
  JWT_ISSUER_UNKNOWN: 'JWT_ISSUER_UNKNOWN',
  // Phase A4 — SCIM + audit export.
  SCIM_INVALID_TOKEN: 'SCIM_INVALID_TOKEN',
  SCIM_RESOURCE_NOT_FOUND: 'SCIM_RESOURCE_NOT_FOUND',
  SCIM_RESOURCE_EXISTS: 'SCIM_RESOURCE_EXISTS',
  SCIM_FILTER_INVALID: 'SCIM_FILTER_INVALID',
  SCIM_PATCH_INVALID: 'SCIM_PATCH_INVALID',
  SCIM_TOKEN_NOT_FOUND: 'SCIM_TOKEN_NOT_FOUND',
  SCIM_TOKEN_REVOKED: 'SCIM_TOKEN_REVOKED',
  AUDIT_EXPORT_DEST_INVALID: 'AUDIT_EXPORT_DEST_INVALID',
  AUDIT_EXPORT_NOT_FOUND: 'AUDIT_EXPORT_NOT_FOUND',
  AUDIT_EXPORT_RUN_FAILED: 'AUDIT_EXPORT_RUN_FAILED',
  // Phase A5 — MFA.
  MFA_REQUIRED: 'MFA_REQUIRED',
  MFA_FACTOR_NOT_FOUND: 'MFA_FACTOR_NOT_FOUND',
  MFA_FACTOR_LOCKED: 'MFA_FACTOR_LOCKED',
  MFA_LAST_FACTOR_PROTECTED: 'MFA_LAST_FACTOR_PROTECTED',
  MFA_LOCKOUT: 'MFA_LOCKOUT',
  MFA_CHALLENGE_INVALID: 'MFA_CHALLENGE_INVALID',
  MFA_CHALLENGE_REPLAY: 'MFA_CHALLENGE_REPLAY',
  TOTP_INVALID_CODE: 'TOTP_INVALID_CODE',
  TOTP_REPLAY_DETECTED: 'TOTP_REPLAY_DETECTED',
  WEBAUTHN_VERIFICATION_FAILED: 'WEBAUTHN_VERIFICATION_FAILED',
  WEBAUTHN_SIGN_COUNT_REGRESSION: 'WEBAUTHN_SIGN_COUNT_REGRESSION',
  WEBAUTHN_USER_VERIFICATION_REQUIRED: 'WEBAUTHN_USER_VERIFICATION_REQUIRED',
  PASSKEY_VERIFICATION_FAILED: 'PASSKEY_VERIFICATION_FAILED',
  PASSKEY_NOT_REGISTERED: 'PASSKEY_NOT_REGISTERED',
  RECOVERY_CODE_INVALID: 'RECOVERY_CODE_INVALID',
  RECOVERY_CODE_USED: 'RECOVERY_CODE_USED',
  RECOVERY_CODES_EXHAUSTED: 'RECOVERY_CODES_EXHAUSTED',
  BYPASS_TOKEN_NOT_FOUND: 'BYPASS_TOKEN_NOT_FOUND',
  BYPASS_TOKEN_EXPIRED: 'BYPASS_TOKEN_EXPIRED',
  BYPASS_TOKEN_USED: 'BYPASS_TOKEN_USED',
  // Phase A6 — SAML 2.0.
  SAML_INVALID_RESPONSE: 'SAML_INVALID_RESPONSE',
  SAML_SIGNATURE_INVALID: 'SAML_SIGNATURE_INVALID',
  SAML_REPLAY_DETECTED: 'SAML_REPLAY_DETECTED',
  SAML_ASSERTION_EXPIRED: 'SAML_ASSERTION_EXPIRED',
  SAML_ASSERTION_NOT_YET_VALID: 'SAML_ASSERTION_NOT_YET_VALID',
  SAML_AUDIENCE_MISMATCH: 'SAML_AUDIENCE_MISMATCH',
  SAML_NAMEID_MISMATCH: 'SAML_NAMEID_MISMATCH',
  SAML_INVALID_METADATA: 'SAML_INVALID_METADATA',
  SAML_SP_KEY_NOT_FOUND: 'SAML_SP_KEY_NOT_FOUND',
  SAML_INRESPONSETO_MISMATCH: 'SAML_INRESPONSETO_MISMATCH',
  // Phase A7 — impersonation.
  IMPERSONATION_REASON_REQUIRED: 'IMPERSONATION_REASON_REQUIRED',
  IMPERSONATION_TICKET_REQUIRED: 'IMPERSONATION_TICKET_REQUIRED',
  IMPERSONATION_NOT_FOUND: 'IMPERSONATION_NOT_FOUND',
  IMPERSONATION_EXPIRED: 'IMPERSONATION_EXPIRED',
  IMPERSONATION_REVOKED: 'IMPERSONATION_REVOKED',
  IMPERSONATION_ENDED: 'IMPERSONATION_ENDED',
  IMPERSONATION_FORBIDDEN_FOR_RESOURCE: 'IMPERSONATION_FORBIDDEN_FOR_RESOURCE',
  IMPERSONATION_REQUIRES_OPERATOR: 'IMPERSONATION_REQUIRES_OPERATOR',
  IMPERSONATION_DURATION_INVALID: 'IMPERSONATION_DURATION_INVALID',
  // Phase A7 — break-glass.
  BREAK_GLASS_REQUIRES_OPERATOR: 'BREAK_GLASS_REQUIRES_OPERATOR',
  BREAK_GLASS_JUSTIFICATION_REQUIRED: 'BREAK_GLASS_JUSTIFICATION_REQUIRED',
  BREAK_GLASS_INCIDENT_REQUIRED: 'BREAK_GLASS_INCIDENT_REQUIRED',
  BREAK_GLASS_GRANT_NOT_FOUND: 'BREAK_GLASS_GRANT_NOT_FOUND',
  BREAK_GLASS_NOT_PENDING: 'BREAK_GLASS_NOT_PENDING',
  BREAK_GLASS_NOT_ACTIVE: 'BREAK_GLASS_NOT_ACTIVE',
  BREAK_GLASS_EXPIRED: 'BREAK_GLASS_EXPIRED',
  BREAK_GLASS_REVOKED: 'BREAK_GLASS_REVOKED',
  BREAK_GLASS_SELF_APPROVAL_FORBIDDEN: 'BREAK_GLASS_SELF_APPROVAL_FORBIDDEN',
  BREAK_GLASS_GRANT_EXCEEDS_AUTHORITY: 'BREAK_GLASS_GRANT_EXCEEDS_AUTHORITY',
  BREAK_GLASS_DURATION_INVALID: 'BREAK_GLASS_DURATION_INVALID',
  // Phase A7 — risk engine.
  RISK_STEP_UP_REQUIRED: 'RISK_STEP_UP_REQUIRED',
  RISK_HARD_DENIED: 'RISK_HARD_DENIED',
} as const;

export type IdentityErrorCode = (typeof codes)[keyof typeof codes];

export class IdentityError extends Error {
  readonly code: IdentityErrorCode;
  readonly status: number;

  constructor(code: IdentityErrorCode, message: string, status = 400) {
    super(message);
    this.name = 'IdentityError';
    this.code = code;
    this.status = status;
  }
}
