/**
 * Identity error taxonomy. Mirrors `@atlas/authz` and
 * `@atlas/content-pages`: a `code` (taxonomy string), human message,
 * suggested HTTP status. The wiring layer maps these to error envelopes.
 */

export const codes = {
  // Phase A1
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_SUSPENDED: 'USER_SUSPENDED',
  MEMBERSHIP_NOT_FOUND: 'MEMBERSHIP_NOT_FOUND',
  MEMBERSHIP_REQUIRED: 'MEMBERSHIP_REQUIRED',
  INVITE_NOT_FOUND: 'INVITE_NOT_FOUND',
  INVITE_EXPIRED: 'INVITE_EXPIRED',
  INVITE_ALREADY_USED: 'INVITE_ALREADY_USED',
  INVITE_REASON_REQUIRED: 'INVITE_REASON_REQUIRED',
  PASSWORD_INVALID: 'PASSWORD_INVALID',
  PASSWORD_COMPLEXITY: 'PASSWORD_COMPLEXITY',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  RATE_LIMITED: 'RATE_LIMITED',
  IDENTITY_INVALID: 'IDENTITY_INVALID',
  // Phase A2 — sessions
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  SESSION_REUSE_DETECTED: 'SESSION_REUSE_DETECTED',
  SESSION_HARD_TIMEOUT: 'SESSION_HARD_TIMEOUT',
  SESSION_IDLE_TIMEOUT: 'SESSION_IDLE_TIMEOUT',
  CSRF_FAILED: 'CSRF_FAILED',
  // Phase A2 — API keys + service principals
  API_KEY_NOT_FOUND: 'API_KEY_NOT_FOUND',
  API_KEY_REVOKED: 'API_KEY_REVOKED',
  API_KEY_EXPIRED: 'API_KEY_EXPIRED',
  API_KEY_SCOPE_INSUFFICIENT: 'API_KEY_SCOPE_INSUFFICIENT',
  API_KEY_MALFORMED: 'API_KEY_MALFORMED',
  SERVICE_PRINCIPAL_NOT_FOUND: 'SERVICE_PRINCIPAL_NOT_FOUND',
  SERVICE_PRINCIPAL_DISABLED: 'SERVICE_PRINCIPAL_DISABLED',
  SERVICE_PRINCIPAL_SCOPE_EXCEEDED: 'SERVICE_PRINCIPAL_SCOPE_EXCEEDED',
  // Phase A2 — OAuth (RFC 6749 error code shape: snake_case strings —
  // wire layer maps these to the OAuth-spec `error` field on the token
  // response).
  OAUTH_INVALID_GRANT: 'OAUTH_INVALID_GRANT',
  OAUTH_INVALID_CLIENT: 'OAUTH_INVALID_CLIENT',
  OAUTH_INVALID_SCOPE: 'OAUTH_INVALID_SCOPE',
  OAUTH_UNSUPPORTED_GRANT_TYPE: 'OAUTH_UNSUPPORTED_GRANT_TYPE',
  OAUTH_TOKEN_EXPIRED: 'OAUTH_TOKEN_EXPIRED',
  OAUTH_TOKEN_REVOKED: 'OAUTH_TOKEN_REVOKED',
} as const;

export type IdentityErrorCode = (typeof codes)[keyof typeof codes];

export class IdentityError extends Error {
  readonly code: IdentityErrorCode;
  readonly status: number;

  constructor(code: IdentityErrorCode, message: string, status = 400) {
    super(message);
    this.name = 'IdentityError';
    this.code = code;
    this.status = status;
  }
}
