/**
 * Static attribute hints for the Cedar editor's autocomplete.
 *
 * The Cedar Schema generated by `@atlas/adapters-policy-cedar` from the
 * bundled module manifest currently emits *empty* entity shapes (audit
 * followup #1 from chunk 6c). Until module manifests grow attribute
 * declarations, the editor sources attribute names from this file so
 * users can type policies that reference attributes the runtime
 * doesn't yet validate. Switching to schema-driven autocomplete is one
 * wiring change once the manifest grows.
 */

export interface AttributeHint {
  name: string;
  type: 'string' | 'number' | 'boolean' | 'set';
  description: string;
}

/** Hints for the User principal entity. */
export const PRINCIPAL_HINTS: readonly AttributeHint[] = [
  { name: 'role', type: 'string', description: "Tenant role (e.g. 'tenant-admin')" },
  { name: 'department', type: 'string', description: 'Org department key' },
  { name: 'email', type: 'string', description: 'Principal email' },
] as const;

/** Hints for module-owned resource entities. Keyed by resourceType. */
export const RESOURCE_HINTS: Readonly<Record<string, readonly AttributeHint[]>> = {
  Family: [
    { name: 'department', type: 'string', description: 'Owning department' },
    { name: 'classification', type: 'string', description: 'Sensitivity class' },
  ],
  Policy: [
    { name: 'status', type: 'string', description: 'draft / active / archived' },
  ],
} as const;

/** Action ids the manifest declares — surfaced as autocomplete completions. */
export const ACTION_HINTS: readonly string[] = [
  'Catalog.SeedPackage.Apply',
  'Catalog.Family.Publish',
  'Catalog.Family.Read',
  'Catalog.Family.Archive',
  'Catalog.Family.Delete',
  'Authz.Policy.List',
  'Authz.Policy.Read',
  'Authz.Policy.Create',
  'Authz.Policy.Activate',
  'Authz.Policy.Archive',
] as const;
